[package]
edition = "2018"
name = "palmrs-database"
version = "0.1.0-dev.1"
license = "MIT OR Apache-2.0"

[dev-dependencies]
env_logger = { version = "0.9.0" }
test-env-log = { version = "0.2.7" }

[dependencies]
byteorder = { version = "1.4" }
chrono = { version = "0.4" }
